require("FFSetup.colorpicker")
require("FFSetup.harpoon")
require("FFSetup.hexcolour")
require("FFSetup.lualine")
require("FFSetup.neotree")
require("FFSetup.noice")
require("FFSetup.silicon")
require("FFSetup.telescope")
