-- Plugin Specific
require("FFKeys.basicSettings")
require("FFKeys.git")
require("FFKeys.harpoon")
require("FFKeys.telescope")
require("FFKeys.undotree")
require("FFKeys.lualine")
require("FFKeys.hexcolour")
require("FFKeys.silicon")
require("FFKeys.colorpicker")
